<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 include 'Base.php';
class Destination extends Base{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Destination_model');
    } 

    /*
     * Listing of destinations
     */
    function index()
    {
        $data['destinations'] = $this->Destination_model->get_all_destinations();
        
        $data['_view'] = 'destination/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new destination
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $destination_id = $this->Destination_model->add_destination($params);
            redirect('destination/index');
        }
        else
        {            
            $data['_view'] = 'destination/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a destination
     */
    function edit($id)
    {   
        // check if the destination exists before trying to edit it
        $data['destination'] = $this->Destination_model->get_destination($id);
        
        if(isset($data['destination']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Destination_model->update_destination($id,$params);            
                redirect('destination/index');
            }
            else
            {
                $data['_view'] = 'destination/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The destination you are trying to edit does not exist.');
    } 

    /*
     * Deleting destination
     */
    function remove($id)
    {
        $destination = $this->Destination_model->get_destination($id);

        // check if the destination exists before trying to delete it
        if(isset($destination['id']))
        {
            $this->Destination_model->delete_destination($id);
            redirect('destination/index');
        }
        else
            show_error('The destination you are trying to delete does not exist.');
    }
    
}
