<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
include 'Base.php'; 
class Login extends Base{
    function __construct()
    {
        parent::__construct();
         $this->load->model('User_model');
        
    }

    function index()

    {
    	if(isset($_SESSION['user'])){
                    redirect(base_url('order'));
                }
            
        

        if(isset($_POST) && count($_POST) > 0) {
            $login = $this->input->post('login', true);
            $pass = $this->input->post('pass', true);
            $user = $this->User_model->get_user_login($login);
            if (isset($user['id']) &&  password_verify($pass,$user['password']) ) {

                session_start();
                $_SESSION['user']=$user;
              	 redirect(base_url('order'));

            }else{
               $data['_view'] = 'login/index';
        		$this->load->view('layouts/login',$data);
            }


        }else {
          $data['_view'] = 'login/index';
          $this->load->view('layouts/login',$data);
        }
        
    }
}
