<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
include 'Base.php';
class Report extends Base
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Report_model');
        $this->load->model('Destination_model');
        $this->load->model('User_model');
    }

    /*
     * Listing of destinations
     */
    function index($ajax = 0)
    {
        if ($_SESSION['user'] == null) {
            redirect('/');
        }
        $month=date('Y-m');
        $data['reports'] = $this->Report_model->get_month_orders($month);

        if(isset($_POST)&& count($_POST) > 0) {
            $month = $_POST['month'];

            $data['reports'] = $this->Report_model->get_month_orders($month);

        }

        if ($ajax == 0) {

            $info{'destination'}=$this->Destination_model->get_all_destinations();
            $data{'destination'}=$this->Destination_model->get_all_destinations();
            $data['users'] = $this->User_model->get_all_users();
            $data['_view'] = 'report/index';
            $this->load->view('layouts/main', $data);

        } else {

            echo $this->load->view('report/index', $data, true);
        }
    }

    /*
     * Adding a new destination
     */
    function pdf()
    {
        $month=date('Y-m');
        if((isset($_POST)&& count($_POST) > 0 )) {
            if(isset($_POST['month'])) {
                $month = $_POST['month'];
            }
            $data['reports'] = $this->Report_model->get_month_orders($month);
            $data{'destination'}=$this->Destination_model->get_all_destinations();
            $data['users'] = $this->User_model->get_all_users();


            $html = $this->load->view('report/pdf',$data, true); //load the pdf.php by passing our data and get all data in $html varriable.

            //actually, you can pass mPDF parameter on this load() function
            $pdf = $this->m_pdf->load();
            //generate the PDF!
            $stylesheet = '<style>'.file_get_contents('assets/themes/home/css/bootstrap.css').'</style>';
            // apply external css
            $pdf->WriteHTML($stylesheet,1);
            $pdf->WriteHTML($html,0);
            $pdf->Output();
            exit;

        }
        else{
            redirect('report');
        }

    }
}