<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Order_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get order by id
     */
    function get_order($id)
    {
        return $this->db->get_where('orders',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all orders
     */
    function get_all_orders()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('orders')->result_array();
    }

    function get_all_orders_user($user)
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get_where('orders', array('id_user' => $user))->result_array();
    }

    function get_all_orders_sort($limit,$offset)
    {
        $query = $this->db->select('*')
            ->from('orders')
            ->limit($limit,$offset)
            ->get();

        return $query->result_array();
    }
    function count_all_orders(){
       return $this->db->count_all('orders');
    }
    function count_all_orders_user($id_user){
        $this->db->where('id_user',$id_user);
        $this->db->from('orders');
        return $this->db->count_all_results();
    }
    function get_all_orders_user_sort($limit,$offset,$user)
    {
        $query = $this->db->select('*')
            ->from('orders')
            ->where('id_user',$user)
            ->limit($limit,$offset)
            ->get();

        return $query->result_array();
    }
        
    /*
     * function to add new order
     */
    function add_order($params)
    {
        $this->db->insert('orders',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update order
     */
    function update_order($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('orders',$params);
    }
    
    /*
     * function to delete order
     */
    function delete_order($id)
    {
        return $this->db->delete('orders',array('id'=>$id));
    }
}
