<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Report_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
    * Get all orders
    */
    function get_month_orders($month)
    {
        $this->db->where('SUBSTRING(date,1,7)', $month);
        $this->db->order_by('date', 'desc');
        return $this->db->get('orders')->result_array();
    }

}